worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    sendfile on;
    server_tokens off;

    upstream php_fpm {
        server app:9000;
    }

    server {
        listen 80;
        server_name _;
        root /var/www/html/public;
        index index.php index.html;

        client_max_body_size 25m;

        location = /up {
            access_log off;
            try_files $uri /index.php?$query_string;
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
            fastcgi_pass php_fpm;
            fastcgi_index index.php;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
