expose_php=Off
memory_limit=256M
upload_max_filesize=20M
post_max_size=25M
max_execution_time=60
max_input_time=60
variables_order=EGPCS
opcache.enable=1
opcache.enable_cli=1
opcache.validate_timestamps=0
opcache.max_accelerated_files=20000
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
