version: '3.7'

services:
  nginx:
    container_name: collabbing_web
    image: nginx:latest
    volumes:
      - ../.:/app
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  php:
    container_name: collabbing_php
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ../.:/app
    working_dir: /app

  postgres:
    container_name: collabbing_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: collabbing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  adminer:
    container_name: collabbing_adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080